import joblib
import os
import numpy as np
from sklearn.linear_model import LogisticRegression
from config.settings import settings
from typing import List, Tuple

class RiskAnalyzer:
    PAYMENT_METHODS = ['credit_card', 'upi', 'wallet', 'net_banking']
    COUNTRIES = ['IN', 'US', 'GB', 'DE', 'AU']

    def __init__(self):
        self.model = None
        self.scaler = None
        self.model_path = settings.ML_MODEL_PATH
        self.scaler_path = settings.SCALER_PATH
        self._load_or_train_model()

    def _load_or_train_model(self):
        model_dir = os.path.dirname(self.model_path)
        if not os.path.exists(model_dir):
            os.makedirs(model_dir)

        if os.path.exists(self.model_path) and os.path.exists(self.scaler_path):
            print(f"Loading ML model from {self.model_path}")
            self.model = joblib.load(self.model_path)
            print(f"Loading scaler from {self.scaler_path}")
            self.scaler = joblib.load(self.scaler_path)
        else:
            print("No ML model or scaler found. Training a dummy model for initialization.")
            # This dummy training is just for startup, it will be overwritten by train_model.py
            # Ensure dummy data matches the feature set generated by _preprocess_transaction_data
            X = np.array([
                [100,  1,0,0,0,  1,0,0,0,0], # Example: amount, pm_features, country_features
                [2500, 0,1,0,0,  0,1,0,0,0],
                [50,   0,0,1,0,  1,0,0,0,0],
                [5000, 1,0,0,0,  0,0,1,0,0],
                [300,  0,0,0,1,  1,0,0,0,0],
            ])
            y = np.array([0, 1, 0, 1, 0])
            self.train_model(X, y)

    def _preprocess_transaction_data(self, transaction_data: dict) -> np.ndarray:
        # This method now correctly combines all features from the Transaction schema
        amount = transaction_data.get("amount", 0.0)
        payment_method = transaction_data.get("payment_method", "")
        pm_features = [1 if pm == payment_method else 0 for pm in self.PAYMENT_METHODS]
        country = transaction_data.get("country", "")
        country_features = [1 if c == country else 0 for c in self.COUNTRIES]
        
        # Combine all features into a single array
        features_list = [amount] + pm_features + country_features
        features = np.array(features_list).reshape(1, -1)
        return features

    def _get_risk_explanations(self, transaction_data: dict, risk_score: float) -> List[str]:
        """Generates human-readable explanations for a high-risk score."""
        explanations = []
        if risk_score < settings.RISK_THRESHOLD:
            return explanations

        if transaction_data.get("amount", 0) > 2000:
            explanations.append("Unusually high transaction amount")
        
        if transaction_data.get("country") != 'IN':
            explanations.append(f"Transaction from a foreign country ({transaction_data.get('country')})")

        if transaction_data.get("payment_method") == 'credit_card' and transaction_data.get("amount", 0) > 1000:
            explanations.append("Large payment via Credit Card")

        if not explanations:
            explanations.append("Transaction pattern matches known fraudulent behavior")

        return explanations

    def analyze_transaction(self, transaction_data: dict) -> Tuple[float, List[str], List[float]]:
        """
        Analyzes a transaction and returns a risk score, a list of explanations, and the scaled features.
        """
        if self.model is None or self.scaler is None:
            print("Warning: ML model or scaler not loaded. Returning default risk score and empty features.")
            return 0.5, ["Model or scaler not loaded"], []

        features = self._preprocess_transaction_data(transaction_data)
        scaled_features = self.scaler.transform(features)
        risk_score = float(self.model.predict_proba(scaled_features)[0][1])
        
        explanations = self._get_risk_explanations(transaction_data, risk_score)
        
        return risk_score, explanations, scaled_features.flatten().tolist()

    def train_model(self, X_train: np.ndarray, y_train: np.ndarray):
        # This method is now primarily for the dummy model. The main training is in train_model.py
        print(f"Training ML model with new data of shape {X_train.shape}...")
        self.model = LogisticRegression(random_state=42, max_iter=1000)
        self.model.fit(X_train, y_train)
        joblib.dump(self.model, self.model_path)
        print(f"ML model trained and saved to {self.model_path}")

    def update_model(self, new_model_path: str):
        if os.path.exists(new_model_path):
            print(f"Updating ML model from {new_model_path}")
            self.model = joblib.load(new_model_path)
            joblib.dump(self.model, self.model_path)
            print("ML model updated successfully.")
        else:
            print(f"Error: New model file not found at {new_model_path}")
