apiVersion: 1

datasources:
  - name: MySQL_Fraud_DB
    type: mysql
    access: proxy
    url: mysql:3306
    user: fraud_user
    database: fraud_detection_db
    secureJsonData:
       password: 'mysecretpassword123'
    jsonData:
       maxOpenConns: 0
       maxIdleConns: 2
       connMaxLifetime: 14400
    isDefault: true
